### PR TITLE
Notifications UI

### PR DESCRIPTION
**Pull request by Mnpn**
This PR adds a notifications screen with notification widgets in it. **This UI should be reused for both elders and caregivers**, just pass different database data.

### Usage
Pass notifications (type `List<NotificationItem>`) to the `Notifications()` page as such:

```dart
import "package:eldercare/pages/notifications.dart";
import "package:eldercare/widgets/notification.dart";
import "package:eldercare/themes/CustomTheme.dart";

List<NotificationItem> notifications = [
    NotificationItem(dot: CustomTheme.yellow, title: "You forgot to eat your lunch today!", description: "We've alerted your caretakers, please try to eat your next one.", read: false, date: DateTime.now()),
    NotificationItem(dot: CustomTheme.blue, title: "You ate your meal", description: "Anna, you marked your lunch as eaten.", read: false, date: DateTime.fromMicrosecondsSinceEpoch(1640901600000000)),
    const NotificationItem(dot: CustomTheme.M_black, title: "You ate your meal", description: "Anna, you marked your breakfast as eaten.", read: true),
    NotificationItem(dot: CustomTheme.red, title: "SOS - Sten Spyfärdig", description: "Sten Spyfärdig has pressed the emergency alarm button!", read: false, urgent: true, date: DateTime.fromMicrosecondsSinceEpoch(0)),
    const NotificationItem(dot: CustomTheme.red, title: "SOS - Sten Spyfärdig", description: "Sten Spyfärdig has pressed the emergency alarm button!", read: false, urgent: true),
    const NotificationItem(dot: CustomTheme.red, title: "SOS - Sten Spyfärdig", description: "Other", read: true, urgent: true),
];

...

PageRouteBuilder(pageBuilder: (context, animation1, animation2) => Notifications(items: notifications), /* etc */ ),

```
Ideally this list will be generated with Firebase data.

`NotificationItem`s take a dot colour, a title, and a read status. Optionally, it can also take a description, date (type `DateTime`) and an "urgent" status (`bool`). The urgency status creates a red SOS-styled notification, so use it for that.

Supplying no `NotificationItem`s (an empty array) displays a text message informing the user that they do not have any.

### Images

While not too important, this also scales well on different display sizes:
<details>
	<summary>Sizing demo</summary >
	
</details>

I have tested it and it also scrolls correctly when containing enough items.

### Extra

This PR also includes a settable variable which we should be able to hook up to the database to hide the notifications screen entirely (and remove it from the navbar), the addition of which was probably outside of the scope of this but oh well. ¯\\\_(ツ)\_/¯

---
To avoid conflicts, please merge #13 before this - which depends on #12.

### CODE REVIEW

**Comment by Mnpn** [comment]
Looks like the tests failed because of missing colours - these are found in #13. I've pushed dark_red, but the others are in the other PR. I don't want to create a merge conflict by trying to add them twice. Please review #13 and we'll rerun the tests here if/when that gets merged :)

**Review by nouradeen — CHANGES_REQUESTED** [review]
footer_menu.dart:49

Check if currectIndex is negativ, then = 0

**Review by axelmagnussen — APPROVED** [review]
LGTM

**Review by nouradeen — APPROVED** [review]
LGTM

**Pull request merged**
