### PR TITLE
Feature/notifications3.0

### PR DESCRIPTION
**Pull request by M-AboWarda**
A simple notification module created!
scheduling a notification on our app have never been easier!

### CODE REVIEW

**Comment by M-AboWarda** [comment]
only initialization should be in main and i made it as compact as possible. Only two rows! 
i know it will conflicts with Nours constant modification to the main :)

**Comment by M-AboWarda** [comment]
I keept Nours main new code and added my initialization!

**Comment by M-AboWarda** [comment]
Yes. absolutely can you change these settings as well?
image

**Review by Mnpn — APPROVED** [review]
LGTM

**Pull request merged**
